### ISSUE TITLE
サンプル群の疑問点

### ISSUE THREAD

**Issue by wisteria0x0f** [altseed/Altseed#139]

**Comment by 0xc02d1e7** [comment]
GeometryObject2D_ArcShape：C#版では色が設定されているがC++版にはない

**Comment by 0xc02d1e7** [comment]
GeometryObject2D_CircleShape：C#版では色が設定されているがC++版にはない

**Comment by 0xc02d1e7** [comment]
Recorder.TakeScreenShot("GeometryObject2D_CircleShape", 30);
とは

**Comment by 0xc02d1e7** [comment]
Keyboard_SingularKeyって要りますかね。
Basicと大差ないような

**Comment by 0xc02d1e7** [comment]
マウスカーソルの位置の取得：このサンプルムービーはカーソルが出てた方がわかりやすいような・・・

**Comment by 0xc02d1e7** [comment]
マウス関連：
Recorder.CaptureScreen("hogehoge", 30, 30, 0.5f, 0.5f);が残っていたりと、いやな予感

**Comment by 0xc02d1e7** [comment]
Sound関連：SEとBGMでどう違うのか

**Comment by 0xc02d1e7** [comment]
Sound.Loop：ループしているのだから
音声が再生終了してるか調べても、常に偽なのでは

**Comment by 0xc02d1e7** [comment]
ポストエフェクト：各エフェクトへのリンクがない。

**Comment by durswd** [comment]
Recorder.CaptureScreen まわりは修正しました

**Comment by NumAniCloud** [comment]
Sound関連のサンプルについて、SEとBGMがどう違うかを分かりやすくしました。
ループのサンプルについて、不要な再生終了のチェックを除去しました。
（ところで、サンプル群の疑問点として１つのissueに複数の疑問点を上げるより、複数のissueを立てたほうが課題を管理しやすいと思います。）

**Comment by wisteria0x0f** [comment]
Sound関連のサンプルすごくいいと思いました。
