### ISSUE TITLE
RectI, RectFの機能拡張

### ISSUE THREAD

**Issue by NumAniCloud** [altseed/Altseed#159]
RectIとRectFの間の変換が欲しい。

また、位置とサイズのベクトルを引数に取るコンストラクタが欲しい。次のようなもの。
```csharp
var position = new Vector2DF(1, 2);
var size = new Vector2DF(10, 10);
RectF rect = new RectF(position, size);
```

**Comment by durswd** [comment]
https://github.com/altseed/Altseed/commit/e9a50d1672b37aeac6108c5f0eb821a26ddc2cc2
