### ISSUE TITLE
NuGetパッケージの不具合

### ISSUE THREAD

**Issue by wisteria0x0f** [altseed/Altseed#184]
**C#版**
ビルド出力フォルダにAltseed_Core.dllがコピーされず、実行すると落ちる

**C++版**
参照が追加されず、リンカエラーになる。
ビルド出力フォルダにAltseed.dllがコピーされない。

ともにver1.1.0の話。VS2015update3にて

**Comment by durswd** [comment]
C#版　デバッグ中
C++版　リンカは自分で書かないといけない。もともとAltseed.dllはC#向けなので存在しない
